### ISSUE TITLE
How can I use this model to find words that are as different as possible from a given word?

### ISSUE THREAD

**Issue by lumenwrites** [jayolson/divergent-association-task#2]
Hi! I'm hoping you could help me out with a task similar to what you have done.

Do you know whether it would be difficult to use this model to generate a list of the most unrelated words, given a word? And the list of the most similar ones?

I'd really appreciate any tips or advice!

**Comment by nathanfarlow** [comment]
Sure, you can download the pre trained word vectors from here: https://github.com/stanfordnlp/GloVe. Parse them in Python. Find the vector corresponding to your word. Finally, loop through all other vectors calculating the cosine difference between them and your chosen word and report the top k.

**Comment by lumenwrites** [comment]
Oh, I see! I think I get how that would work. Thank you very much for your help!
